name: Formula update PR

on:
  workflow_dispatch:
    inputs:
      tool:
        description: "Tool name"
        required: true
      tag:
        description: "Tool version tag (vX.Y.Z)"
        required: true
      hash:
        description: "Commit hash"
        required: true

permissions:
  contents: read

jobs:
  pr:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ⬇️ Set up gitsign
        uses: chainguard-dev/actions/setup-gitsign@3e76343fe029f8e2a10bfbec0da8f437e5dab7a5 # main
      - name: 📝 Update formula
        run: |
          sudo apt install gettext-base
          envsubst < .github/templates/$TOOL.rb.template > Formula/$TOOL.rb
        env:
          TOOL: ${{ github.event.inputs.tool }}
          TAG: ${{ github.event.inputs.tag }}
          HASH: ${{ github.event.inputs.hash }}
      - name: 🏗️ Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          committer: "Outscale Bot <opensource+bot@outscale.com>"
          author: "Outscale Bot <opensource+bot@outscale.com>"
          commit-message: "🚀 ${{ env.tool }} ${{ env.tag }}"
          body: |
            Automatic PR based on tool release.
          title: "🚀 ${{ env.tool }} ${{ env.tag }}"
          token: "${{ env.token }}"
          labels: "kind/feature"
        env:
          tool: ${{ github.event.inputs.tool }}
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.CREATE_PR_TOKEN }}
